### ISSUE TITLE
Twitto 2.0 roadmap

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#76]
Re-develop twitto from scratch, as a real-time dashboard.

Use twitter's streaming API to get tweets geolocated in Belgium, and stream those in real time to client-side.

#### In the roadmap for 2.0.0:

- [ ] design dashboard #78
- [x] setup css framework #77 #82 
- [x] setup express #79
- [x] filter Belgian tweets #80
- [x] persist data #86 
- [x] show tweets in a map in real time #81 #83
- [ ] show live statistics about the tweets #85 #87
- [ ] copywriting #91 
- [x] dev convenience: live-reload #92 
- [ ] production setup #96
- [ ] error pages #97
- [ ] loading spinners #98

#### Backlog

- [ ] #88 responsive charts tuning
- [ ] #89 map enhancement (zoomed-in area)
- [ ] #90 code cleanup

**Comment by mef** [comment]
Status:

Memory leak on the server is preventing 2.0.0 to be released.

Priorities after that are:

* mentions and hashtags #85 
* performance tuning client side #84

**Comment by mef** [comment]
Heads-up @11digitlabs :

* last commit modifies the data structure, you have to delete the content of `persist/` directory after pulling
* API change for map data: coordinates are now inside `tweet.coordinates` instead of tweet.twitto.coordinates`
* API change for donut chart data: use property `tweet.is_reply` instead of check of `tweet.in_reply_to_user_id`

**Comment by mef** [comment]
Status update:

* memory consumption on the server now seems much more reasonable.
* regression in tweets per minute timeline chart

Will release if server behaves well after 24h uptime

**Comment by mef** [comment]
Hey @11digitlabs I've created a github project for twitto, looks convenient to manage statuses.

Please have a look, to me it seems that we can use it to replace the started / please test / tested OK tags.
